# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_auto_20170311_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_material',
            old_name='unit',
            new_name='item',
        ),
    ]
