# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_remove_material_transactions_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_transactions',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sos.Invoice'),
            preserve_default=False,
        ),
    ]
