# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_auto_20170307_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='name',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
