# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_auto_20170226_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
