# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_auto_20170307_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='org_nbr',
            new_name='org_nbr_1',
        ),
        migrations.AddField(
            model_name='organization',
            name='org_nbr_2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
