# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_auto_20170314_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_type', to='sos.Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment_method', to='sos.Code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_status', to='sos.Code'),
        ),
    ]
