# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_material_transactions_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parrent_name', models.ManyToManyField(related_name='_material_group_parrent_name_+', to='sos.Material_Group')),
            ],
            options={
                'verbose_name': 'Material Group',
                'verbose_name_plural': 'Material Groups',
            },
        ),
    ]
