# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_auto_20170308_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='code',
            new_name='org_type',
        ),
    ]
