# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_auto_20170314_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.Invoice')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.Material')),
            ],
            options={
                'verbose_name': 'Material Transaction',
                'verbose_name_plural': 'Material Transactions',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.AddField(
            model_name='material_transactions',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.Warehouse'),
        ),
    ]
