# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0005_auto_20170226_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sos.Organization'),
            preserve_default=False,
        ),
    ]
