# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0005_organization_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='bank_account',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
