# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0005_auto_20170308_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_dealer', to='sos.Organization')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.Code')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_manufacturer', to='sos.Organization')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.Tax')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
