# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0006_auto_20170407_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_group',
            name='parrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sos.Material_Group'),
        ),
    ]
