# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0006_auto_20170308_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice_details',
            options={'verbose_name': 'Invoice detail', 'verbose_name_plural': 'Invoice details'},
        ),
        migrations.AddField(
            model_name='invoice_details',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sos.Material'),
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sos.Service'),
        ),
        migrations.AlterField(
            model_name='material',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_dealer', to='sos.Organization'),
        ),
        migrations.AlterField(
            model_name='material',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_manufacturer', to='sos.Organization'),
        ),
    ]
