# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0007_auto_20170308_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_details',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
