# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0007_auto_20170503_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sos.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='is_client',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_dealer',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_manufacturer',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_owner',
            field=models.NullBooleanField(),
        ),
    ]
