# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0008_auto_20170227_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='parrent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
