# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0010_auto_20170620_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sos.Manufacturer'),
            preserve_default=False,
        ),
    ]
