# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0011_auto_20170620_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_material',
            old_name='item',
            new_name='quantity',
        ),
    ]
