# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0014_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='add_code1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='add_code2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='add_code3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='add_code4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
