# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0018_auto_20170803_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sales_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
